      # Use postgres/example user/password credentials
      version: '3.1'

      services:

        db:
          image: postgres
          ports:
            - '9999:9999'
          volumes:
            - /var/lib/postgresql/data
          restart: always
          environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef

