      # Use postgres/example user/password credentialds
      version: '3.1'

      services:

        db:
          image: postgres
          ports:
            - '5432:5432'
          volumes:
            - ./data:/var/lib/postgresql/data
          restart: always
          environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef

